[workspace]
members = [
    "backends/aws-lambda/host",
    "backends/aws-lambda/guest",
    "core",
    "core/guest",
    "core/entity",
    "core/iomod",
    "core/iomod/guest",
    "core/io",
    "core/io/guest",
    "core/io/common",
    "cli"
]
