[package]
name = "assemblylift-core"
version = "0.4.0-alpha.12"
description = "AssemblyLift core library"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
itertools = "0.10"
once_cell = "1.4"
tokio = "1.4"
z85 = "3"

wasmtime = "4.0"
wasmtime-wasi = "4.0"

assemblylift-core-io-common = { version = "0.3", path = "./io/common" }
assemblylift-core-iomod = { version = "0.4.0-alpha.10", path = "./iomod" }
