[project]
name = "custom-domain"

[[services]]
name = "example"

[[domains]]
dns_name = "example.com"
# map_to_root = true # Set to omit project name from URL
[domains.provider]
name = "route53"
[domains.provider.options]
aws_region = "us-east-1"
