[entity]
name = "user"

[[fields]]
name = "name"
type = "string"
attributes = ["searchable"] # Optional

[[fields]]
name = "email"
type = "string"
attributes = ["unique", "primary"] # Optional

[[actions]]
action = "load"
[actions.cap]
location = "asml/service/service-name/*"
origins = ["asml/*"]
effect = "allow"

[[actions]]
action = "store"
[actions.cap]
location = "dynamodb/region/table-name"
origins = ["asml/*"]
effect = "allow"

#[[policies]]
#name = "policy-name"
#type = "opa" # always OPA
#file = "/path/to/file.rego" # file XOR from
#from = """
#package example
#default allow = false
#"""
